import type { TeamBlueprint, TeamBlueprintCatalogView } from "@squadrail/shared";

const DEFAULT_TEAM_BLUEPRINTS: TeamBlueprint[] = [
  {
    key: "small_delivery_team",
    label: "Small Delivery Team",
    description:
      "A compact delivery squad with one tech lead, one engineer, and one reviewer for a single primary workspace.",
    presetKey: "squadrail_default_v1",
    projects: [
      {
        key: "primary_product",
        label: "Primary Product",
        description: "Single delivery project for the company's first production workspace.",
        kind: "product",
        repositoryHint: "Connect one main repository workspace before the first quick request.",
        defaultLeadRoleKey: "tech_lead",
      },
    ],
    roles: [
      {
        key: "tech_lead",
        label: "Tech Lead",
        role: "engineer",
        title: "Tech Lead",
        reportsToKey: null,
        projectBinding: "shared",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["scoping", "task routing", "review bar"],
      },
      {
        key: "engineer",
        label: "Engineer",
        role: "engineer",
        title: "Engineer",
        reportsToKey: "tech_lead",
        projectBinding: "shared",
        preferredAdapterTypes: ["codex_local", "claude_local"],
        deliveryLane: "implementation",
        capabilities: ["implementation", "focused testing", "handoff notes"],
      },
      {
        key: "reviewer",
        label: "Reviewer",
        role: "engineer",
        title: "Reviewer",
        reportsToKey: "tech_lead",
        projectBinding: "shared",
        preferredAdapterTypes: ["claude_local", "codex_local"],
        deliveryLane: "review",
        capabilities: ["review", "risk capture", "close evidence"],
      },
    ],
    parameterHints: {
      supportsPm: false,
      supportsQa: false,
      supportsCto: false,
      defaultProjectCount: 1,
      defaultEngineerPairsPerProject: 1,
    },
    readiness: {
      requiredWorkspaceCount: 1,
      knowledgeRequired: true,
      knowledgeSources: ["project_docs", "codebase", "past_issues"],
      approvalRequiredRoleKeys: ["tech_lead"],
      doctorSetupPrerequisites: ["workspace_connected", "execution_engine_selected", "doctor_clean"],
      recommendedFirstQuickRequest:
        "Review the connected repository, confirm the workspace is healthy, and propose the first delivery slice with explicit acceptance criteria.",
    },
  },
  {
    key: "standard_product_squad",
    label: "Standard Product Squad",
    description:
      "A product squad with PM coordination, one lead per project, delivery engineers, and reviewers across two default projects.",
    presetKey: "example_product_squad_v1",
    projects: [
      {
        key: "product_app",
        label: "Product App",
        description: "Customer-facing application or frontend repository.",
        kind: "product",
        repositoryHint: "Connect the primary app workspace and documentation for release-facing issues.",
        defaultLeadRoleKey: "app_tech_lead",
      },
      {
        key: "product_api",
        label: "Product API",
        description: "Backend or service repository paired with the product app.",
        kind: "service",
        repositoryHint: "Connect the backend workspace and seed API docs before intake projection.",
        defaultLeadRoleKey: "backend_tech_lead",
      },
    ],
    roles: [
      {
        key: "pm",
        label: "PM",
        role: "pm",
        title: "PM",
        reportsToKey: null,
        projectBinding: "none",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["requirements_structuring", "clarification", "projection"],
      },
      {
        key: "app_tech_lead",
        label: "App Tech Lead",
        role: "engineer",
        title: "Tech Lead",
        reportsToKey: "pm",
        projectBinding: "per_project",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["task_breakdown", "handoff", "review_routing"],
      },
      {
        key: "backend_tech_lead",
        label: "Backend Tech Lead",
        role: "engineer",
        title: "Tech Lead",
        reportsToKey: "pm",
        projectBinding: "per_project",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["task_breakdown", "integration_scope", "review_routing"],
      },
      {
        key: "engineer",
        label: "Engineer",
        role: "engineer",
        title: "Engineer",
        reportsToKey: "app_tech_lead",
        projectBinding: "per_project",
        preferredAdapterTypes: ["codex_local", "claude_local"],
        deliveryLane: "implementation",
        capabilities: ["implementation", "tests", "evidence_capture"],
      },
      {
        key: "reviewer",
        label: "Reviewer",
        role: "engineer",
        title: "Reviewer",
        reportsToKey: "pm",
        projectBinding: "per_project",
        preferredAdapterTypes: ["claude_local", "codex_local"],
        deliveryLane: "review",
        capabilities: ["review", "risk_identification", "close_readiness"],
      },
    ],
    parameterHints: {
      supportsPm: true,
      supportsQa: false,
      supportsCto: false,
      defaultProjectCount: 2,
      defaultEngineerPairsPerProject: 1,
    },
    readiness: {
      requiredWorkspaceCount: 2,
      knowledgeRequired: true,
      knowledgeSources: ["product_docs", "api_docs", "codebase", "past_issues"],
      approvalRequiredRoleKeys: ["pm", "app_tech_lead", "backend_tech_lead"],
      doctorSetupPrerequisites: [
        "workspace_connected_for_each_project",
        "knowledge_seeded_for_primary_projects",
        "doctor_clean",
      ],
      recommendedFirstQuickRequest:
        "Take one customer-visible request, let PM turn it into an execution-ready issue, and route it through app or backend TL ownership with reviewer evidence.",
    },
  },
  {
    key: "delivery_plus_qa",
    label: "Delivery + QA Team",
    description:
      "A reusable delivery organization with PM, QA, multiple project leads, and reviewer coverage for release-sensitive work.",
    presetKey: "example_large_org_v1",
    projects: [
      {
        key: "app_surface",
        label: "App Surface",
        description: "Primary application repository for user-facing delivery.",
        kind: "product",
        repositoryHint: "Connect the app workspace and release notes knowledge source.",
        defaultLeadRoleKey: "product_tech_lead",
      },
      {
        key: "platform_services",
        label: "Platform Services",
        description: "Backend, worker, or platform service repository.",
        kind: "service",
        repositoryHint: "Connect backend and worker workspaces before enabling QA loops.",
        defaultLeadRoleKey: "platform_tech_lead",
      },
    ],
    roles: [
      {
        key: "cto",
        label: "CTO",
        role: "cto",
        title: "CTO",
        reportsToKey: null,
        projectBinding: "none",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "oversight",
        capabilities: ["cross_project_orchestration", "final_review_synthesis", "risk_escalation"],
      },
      {
        key: "pm",
        label: "PM",
        role: "pm",
        title: "PM",
        reportsToKey: "cto",
        projectBinding: "none",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["intake_structuring", "clarification", "projection"],
      },
      {
        key: "qa_lead",
        label: "QA Lead",
        role: "qa",
        title: "QA Lead",
        reportsToKey: "cto",
        projectBinding: "shared",
        preferredAdapterTypes: ["claude_local", "codex_local"],
        deliveryLane: "qa",
        capabilities: ["release_safety", "qa_bar", "regression_triage"],
      },
      {
        key: "product_tech_lead",
        label: "Product Tech Lead",
        role: "engineer",
        title: "Tech Lead",
        reportsToKey: "pm",
        projectBinding: "per_project",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["task_breakdown", "review_routing", "implementation_scope"],
      },
      {
        key: "platform_tech_lead",
        label: "Platform Tech Lead",
        role: "engineer",
        title: "Tech Lead",
        reportsToKey: "pm",
        projectBinding: "per_project",
        preferredAdapterTypes: ["claude_local"],
        deliveryLane: "planning",
        capabilities: ["cross_service_scope", "review_routing", "integration_risk"],
      },
      {
        key: "engineer",
        label: "Engineer",
        role: "engineer",
        title: "Engineer",
        reportsToKey: "product_tech_lead",
        projectBinding: "per_project",
        preferredAdapterTypes: ["codex_local", "claude_local"],
        deliveryLane: "implementation",
        capabilities: ["implementation", "focused_testing", "handoff_notes"],
      },
      {
        key: "reviewer",
        label: "Reviewer",
        role: "engineer",
        title: "Reviewer",
        reportsToKey: "qa_lead",
        projectBinding: "per_project",
        preferredAdapterTypes: ["claude_local", "codex_local"],
        deliveryLane: "review",
        capabilities: ["review", "qa_handoff", "change_bar"],
      },
    ],
    parameterHints: {
      supportsPm: true,
      supportsQa: true,
      supportsCto: true,
      defaultProjectCount: 2,
      defaultEngineerPairsPerProject: 1,
    },
    readiness: {
      requiredWorkspaceCount: 2,
      knowledgeRequired: true,
      knowledgeSources: ["release_docs", "codebase", "past_issues", "review_outcomes"],
      approvalRequiredRoleKeys: ["cto", "pm", "qa_lead", "product_tech_lead", "platform_tech_lead"],
      doctorSetupPrerequisites: [
        "workspace_connected_for_each_project",
        "knowledge_seeded_for_each_project",
        "review_and_qa_agents_ready",
        "doctor_clean",
      ],
      recommendedFirstQuickRequest:
        "Use a release-sensitive issue that requires PM clarification, TL delegation, reviewer evidence, and QA sign-off before closure.",
    },
  },
];

export function listTeamBlueprints(): TeamBlueprint[] {
  return DEFAULT_TEAM_BLUEPRINTS.map((blueprint) => ({
    ...blueprint,
    projects: blueprint.projects.map((project) => ({ ...project })),
    roles: blueprint.roles.map((role) => ({
      ...role,
      preferredAdapterTypes: [...role.preferredAdapterTypes],
      capabilities: [...role.capabilities],
    })),
    parameterHints: { ...blueprint.parameterHints },
    readiness: {
      ...blueprint.readiness,
      knowledgeSources: [...blueprint.readiness.knowledgeSources],
      approvalRequiredRoleKeys: [...blueprint.readiness.approvalRequiredRoleKeys],
      doctorSetupPrerequisites: [...blueprint.readiness.doctorSetupPrerequisites],
    },
  }));
}

export function teamBlueprintService() {
  return {
    getCatalog(companyId: string): TeamBlueprintCatalogView {
      return {
        companyId,
        blueprints: listTeamBlueprints(),
      };
    },
  };
}
